apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
  labels:
    app: gitops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: gitops-app
        image: dockerhub-username/gitops-app:latest   # ðŸ”‘ This will be updated by GitHub Actions
        ports:
        - containerPort: 80
